name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-10.15, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          platform: ${{ matrix.os }}
          output-dir: wheelhouse
          build: --no-zstd

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
