name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          wget https://litesync.io/download/litesync-free-linux-x86_64.tar.gz
          tar -xzvf litesync-free-linux-x86_64.tar.gz
          sudo ./install

      - name: Install build dependencies
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri https://litesync.io/download/litesync-free-windows-x86_64.tar.gz -OutFile litesync-free-windows-x86_64.zip
          Expand-Archive -Path litesync-free-windows-x86_64.zip -DestinationPath .
          install.bat

      - name: Install build dependencies
        if: matrix.os == 'macos-latest'
        run: |
          # Install sqlite3 via brew
          brew update
          wget https://litesync.io/download/litesync-free-mac-x86_64.tar.gz
          tar -xzvf litesync-free-mac-x86_64.tar.gz
          ./install

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

          # - name: Build wheels
          # run: python3 cibuildwheel --output-dir wheelhouse
      
      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse
