name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-10.15, macos-11.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          build: |
            python setup.py build_ext --include-dirs=/usr/local/include --library-dirs=/usr/local/lib
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

